### ISSUE TITLE
TT1 Blocks: Issues with images not stretching full-width

### ISSUE THREAD

**Issue by alaczek** [WordPress/theme-experiments#192] opened 2021-02-02 00:36 UTC
I saw two issues - one in the Image block, other in the Cover block, which I think are connected. I'm happy to open separate tickets if that helps. Basically, the images in both instances don't stretch the full-width, when the block is set to full-width.

TT1 blocks: 
![image](https://user-images.githubusercontent.com/4550351/106535586-b0047700-654a-11eb-9401-20fc1cc70503.png)

Code I'm working with:
```
<!-- wp:heading {"level":3} -->
<h3>Full-width Image</h3>
<!-- /wp:heading -->

<!-- wp:image {"align":"full","id":35,"sizeSlug":"large","linkDestination":"none"} -->
<figure class="wp-block-image alignfull size-large"><img src="https://wide-tahr.jurassic.ninja/wp-content/uploads/2021/01/pattern-art-1024x771.jpg" alt="" class="wp-image-35"/></figure>
<!-- /wp:image -->

<!-- wp:heading -->
<h2>Cover block</h2>
<!-- /wp:heading -->

<!-- wp:cover {"url":"https://wide-tahr.jurassic.ninja/wp-content/uploads/2021/01/bench-accounting-nvzvopqw0gc-unsplash.jpg","id":21,"align":"full"} -->
<div class="wp-block-cover alignfull has-background-dim"><img class="wp-block-cover__image-background wp-image-21" alt="" src="https://wide-tahr.jurassic.ninja/wp-content/uploads/2021/01/bench-accounting-nvzvopqw0gc-unsplash.jpg" data-object-fit="cover"/><div class="wp-block-cover__inner-container"><!-- wp:heading {"textAlign":"center","level":3} -->
<h3 class="has-text-align-center">New posts in your inbox</h3>
<!-- /wp:heading --></div></div>
<!-- /wp:cover -->
```

WordPress 5.6
Gutenberg plugin: 9.8.3
TT1 Blocks: 0.4.2

**Comment by kjellr** [comment] 2021-02-02 14:14
👋 I _think_ [this is fixed in the latest version in this repo](https://github.com/WordPress/theme-experiments/pull/174) (which is yet to be uploaded anywhere because it depends on Gutenberg 9.9 being released later this week).

**Comment by carolinan** [comment] 2021-05-12 11:59
I have not been able to reproduce this, in Chrome or Firefox on PC.  Closing.

**Closed by carolinan** 2021-05-12 11:59 UTC
